import Link from "next/link";
import type { Metadata } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-space-grotesk",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "Login", href: "/auth" },
  { label: "Register", href: "/register" },
  { label: "Consent", href: "/consent" },
  { label: "Enroll", href: "/enroll" },
  { label: "Vote", href: "/vote" },
  { label: "History", href: "/history" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${spaceMono.variable} antialiased bg-slate-950 text-white`}
      >
        <div className="flex w-full flex-col">
          <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/80 backdrop-blur">
            <div className="mx-auto flex max-w-[1200px] items-center justify-between px-4 py-4">
              <div className="flex flex-col">
                <span className="text-xs uppercase tracking-[0.4em] text-muted-foreground">
                  The Official Voting App
                </span>
                <strong className="text-lg font-semibold leading-tight text-white">
                  Maghreb Vote
                </strong>
              </div>
              <nav className="flex items-center gap-2 text-sm uppercase tracking-[0.25em]">
                {navItems.map((navItem) => (
                  <Link
                    key={navItem.href}
                    href={navItem.href}
                    className="rounded-full border border-white/10 px-4 py-2 transition hover:border-white"
                  >
                    {navItem.label}
                  </Link>
                ))}
              </nav>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
